server:
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    org:
      springframework:
        security: DEBUG

spring:
#  cache:
#    type: none
  datasource:
    url: jdbc:postgresql://ella.db.elephantsql.com:5432/lvtjlbwh
    username: lvtjlbwh
    password: zzRV4A2Bj5aa18cMkOMJi4l_xrZooCw_
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true